version: '3.8'
services:
  curso-api:
    image: curso-api
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
    depends_on:
      - postgres-db
  postgres-db:
    image: postgres:16
    environment:
      - POSTGRES_USER=edicao_cursos_user
      - POSTGRES_PASSWORD=ZJLs821sNs1EARL0qAtXENqI2ASFmqk
      - POSTGRES_DB=edicao_cursos
    ports:
      - "5432:5432"